---
- hosts: dockerhost
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
    - name: Install pip
      apt: name=python-pip state=upgrade
    - name: Verify PIP version
      command: pip --version
    - name: Création du dossier db_data
      command: mkdir db_data
