---
- hosts: dockerhost
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
    - name: install docker-py
      pip: name=docker-py
    - name: verify docker-py version
      command: pip list | egrep 'docker'
