---
- hosts: dockerhost
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
    - name: Cleaning Home Directory
      command: rm -rf *
    - name: Install pip
      apt: name=python-pip state=latest
    - name: Verify PIP version
      command: pip --version
      command: echo " PIP est bien installé ..."
    - name: Création des dossiers db_data
      command: mkdir db_data
