---
- hosts: dockerhost
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
    - name: Install pip
      apt: name=python-pip state=latest
    - name: Verify PIP version
      command: pip --version
    - name: Création des dossiers db_data et ghost
      command: mkdir db_data && mkdir ghost
