---
  - hosts: dockerhost
    remote_user: vagrant
    become: yes
    become_method: sudo
    tasks:
      - name: Copie des fichiers Docker        
        template: src=../docker/docker-compose.yml dest=/home/vagrant
        template: src=../docker/Dockerfile dest=/home/vagrant
      - name: Provisionning des services
        action: shell docker-compose up -d

