---
  - hosts: dockerhost
    remote_user: vagrant
    become: yes
    become_method: sudo
    tasks:
      - name: Copie des fichiers docker        
        template: src=./docker/ dest=/home/vagrant
      - name: Provisionning des services
        action: shell docker-compose up -d

