---
  - hosts: dockerhost
    remote_user: vagrant
    become: yes
    become_method: sudo
    tasks:
      - name: Launch docker-compose file        
        docker_service:
          project_src: ./docker
    #build: yes
