---
  - hosts: dockerhost
    remote_user: vagrant
    become: yes
    become_method: sudo
    tasks:
      - name: Copie du fichier docker compose        
        template: src=../docker/docker-compose.yml dest=/home/vagrant
      - name: Copie du fichier Dockerfile
        template: src=../docker/Dockerfile dest=/home/vagrant
      - name: Copie du dossier de configuration de node
        template: src=../ghost/ dest=/home/vagrant/ghost/
      - name: Provisionning des services
        action: shell docker-compose up -d

